# Generated by Django 3.1.5 on 2021-01-31 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='person_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='person_tail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bheja', to=settings.AUTH_USER_MODEL),
        ),
    ]
