# Generated by Django 3.1.5 on 2021-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210131_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='person_head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='person_tail',
            field=models.CharField(max_length=50),
        ),
    ]
