# Generated by Django 3.1.5 on 2021-02-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210131_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_head', models.CharField(max_length=50)),
                ('person_tail', models.CharField(max_length=50)),
                ('unread_msg_present', models.IntegerField(default=0)),
                ('unread_msg_previous', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
